### ISSUE TITLE
Error with relative smooth curveto command

### ISSUE THREAD

**Issue by marcprux** [GenerallyHelpfulSoftware/Scalar2D#4]
Given the "relatively" simple path from https://fontawesome.com/icons/adjust

```svg
M8 256c0 136.966 111.033 248 248 248s248-111.034 248-248S392.966 8 256 8 8 119.033 8 256zm248 184V72c101.705 0 184 82.311 184 184 0 101.705-82.311 184-184 184z
```

The path that Scalar2D parses looks like:

<img width="474" alt="Screen Shot 2019-03-20 at 10 30 35" src="https://user-images.githubusercontent.com/659086/54692324-36e90b80-4afb-11e9-94e1-71352fe1e5e3.png">

It may have something to do with the relative coordinates, since if I convert them to absolute coordinates (using the handy tool at https://codepen.io/thednp/pen/EgVqLw) as so:

```svg
M8,256C8,392.966,119.033,504,256,504S504,392.966,504,256S392.966,8,256,8S8,119.033,8,256ZM256,440V72C357.705,72,440,154.311,440,256C440,357.705,357.68899999999996,440,256,440Z
```

Then the path is created correctly:

<img width="525" alt="Screen Shot 2019-03-20 at 10 30 52" src="https://user-images.githubusercontent.com/659086/54692355-40727380-4afb-11e9-98c5-5842a1c8efc6.png">

This library is otherwise fantastic; very fast, and it seems to be the only one out there that can handle "A" and "a" arc path elements.

**Comment by marcprux** [comment]
It seems to have to do with the relative smooth curve command near the beginning. If I replace just:

```svg
s248-111.034 248-248
```

with the absolute equivalent:

```svg
S504,392.966,504,256
```

then it created the path correctly.

**Comment by grhowes** [comment]
Thanks for the pull request. I’ll have to add this to a test case.
