### ISSUE TITLE
Error when continuation command starts with period

### ISSUE THREAD

**Issue by marcprux** [GenerallyHelpfulSoftware/Scalar2D#6]
The following path throws a `PathToken.FailureReason.unexpectedCharacter` error:

```svg
M0,0 L1.2 3 .4 5.6 z
```

Whereas the following equivalent paths work fine:

```svg
M0,0 L1.2 3 0.4 5.6 z
```

or

```svg
M0,0 L1.2 3 L.4 5.6 z
```

An example of a real-world path that uses this construct is https://fontawesome.com/icons/fish

**Comment by grhowes** [comment]
So it’s not handling a leading period maybe?

**Comment by marcprux** [comment]
It seems to handle the period fine when it is in the first parameter. E.g., this works:

```svg
M0,0 L .4 5.6 z
```

But if it is in a subsequent parameter, then it fails:

```svg
M0,0 L1.2 3 .4 5.6 z
```

The error is being thrown from https://github.com/GenerallyHelpfulSoftware/Scalar2D/blob/07673118e550cecad2cd7d303f88e98d2a17dd01/GraphicPath/Source/PathGenerator.swift#L238 , but I can't quite figure out why it happens for a secondary parameter set but not for any others.

**Comment by marcprux** [comment]
What is odd is when there is no whitespace before the dot ("3.0.4"), then the parse is successful:

```svg
M0,0 L1.2 3.0.4 5.6 z
```

**Comment by grhowes** [comment]
OK, I've put in a change. Please verify that it fixes the issue. Thank you again for the report.

**Comment by marcprux** [comment]
Your fix addresses the examples I gave, but it still fails for `M0,0L.1.2.1.2Z` (whereas my fix also handles that case).
